### ISSUE TITLE
line 8: syntax error

### ISSUE THREAD

**Issue by sega-G14** [anthumchris/nginx-macos#1]
install.sh: line 8: syntax error near unexpected token `newline'

<img width="463" alt="2023-04-30 в 23 14 09" src="https://user-images.githubusercontent.com/113241423/235369535-b3464a82-822a-454f-b2e0-c86d00f0ff29.png">

**Comment by anthumchris** [comment]
@sega-G14 Please consider providing your environment info for other users who may experience your issue.

I could not reproduce on my end:

```sh
$ git clone -q git@github.com:anthumchris/nginx-macos.git && cd nginx-macos && ./install.sh
Nginx will build and install at the location below. This should complete in < 5 minutes.

    /tmp/nginx-macos/build/nginx

Start installation? [y/n] n
```

**Comment by sega-G14** [comment]
It all worked out. Thank you!
